package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA



import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AspnetApplications generated by hbm2java
 */
@Entity
@Table(name="aspnet_applications"
    ,schema="public"
    , uniqueConstraints = {@UniqueConstraint(columnNames="applicationname"), @UniqueConstraint(columnNames="loweredapplicationname")} 
)
public class AspnetApplications  implements Serializable{


     private String applicationid;
     private String applicationname;
     private String loweredapplicationname;
     private String description;
     private Set<AspnetUsers> aspnetUserses = new HashSet<AspnetUsers>(0);
     private Set<AspnetPaths> aspnetPathses = new HashSet<AspnetPaths>(0);
     private Set<AspnetRoles> aspnetRoleses = new HashSet<AspnetRoles>(0);
     private Set<AspnetMembership> aspnetMemberships = new HashSet<AspnetMembership>(0);

    public AspnetApplications() {
    }

	
    public AspnetApplications(String applicationid, String applicationname, String loweredapplicationname) {
        this.applicationid = applicationid;
        this.applicationname = applicationname;
        this.loweredapplicationname = loweredapplicationname;
    }
    public AspnetApplications(String applicationid, String applicationname, String loweredapplicationname, String description, Set<AspnetUsers> aspnetUserses, Set<AspnetPaths> aspnetPathses, Set<AspnetRoles> aspnetRoleses, Set<AspnetMembership> aspnetMemberships) {
       this.applicationid = applicationid;
       this.applicationname = applicationname;
       this.loweredapplicationname = loweredapplicationname;
       this.description = description;
       this.aspnetUserses = aspnetUserses;
       this.aspnetPathses = aspnetPathses;
       this.aspnetRoleses = aspnetRoleses;
       this.aspnetMemberships = aspnetMemberships;
    }
   
     @Id 
    
    @Column(name="applicationid", unique=true, nullable=false)
    public String getApplicationid() {
        return this.applicationid;
    }
    
    public void setApplicationid(String applicationid) {
        this.applicationid = applicationid;
    }
    
    @Column(name="applicationname", unique=true, nullable=false, length=256)
    public String getApplicationname() {
        return this.applicationname;
    }
    
    public void setApplicationname(String applicationname) {
        this.applicationname = applicationname;
    }
    
    @Column(name="loweredapplicationname", unique=true, nullable=false, length=256)
    public String getLoweredapplicationname() {
        return this.loweredapplicationname;
    }
    
    public void setLoweredapplicationname(String loweredapplicationname) {
        this.loweredapplicationname = loweredapplicationname;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="aspnetApplications")
    public Set<AspnetUsers> getAspnetUserses() {
        return this.aspnetUserses;
    }
    
    public void setAspnetUserses(Set<AspnetUsers> aspnetUserses) {
        this.aspnetUserses = aspnetUserses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="aspnetApplications")
    public Set<AspnetPaths> getAspnetPathses() {
        return this.aspnetPathses;
    }
    
    public void setAspnetPathses(Set<AspnetPaths> aspnetPathses) {
        this.aspnetPathses = aspnetPathses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="aspnetApplications")
    public Set<AspnetRoles> getAspnetRoleses() {
        return this.aspnetRoleses;
    }
    
    public void setAspnetRoleses(Set<AspnetRoles> aspnetRoleses) {
        this.aspnetRoleses = aspnetRoleses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="aspnetApplications")
    public Set<AspnetMembership> getAspnetMemberships() {
        return this.aspnetMemberships;
    }
    
    public void setAspnetMemberships(Set<AspnetMembership> aspnetMemberships) {
        this.aspnetMemberships = aspnetMemberships;
    }




}


