package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AspnetPersonalizationperuser generated by hbm2java
 */
@Entity
@Table(name="aspnet_personalizationperuser"
    ,schema="public"
)
public class AspnetPersonalizationperuser  implements Serializable {


     private String id;
     private AspnetPaths aspnetPaths;
     private AspnetUsers aspnetUsers;
     private byte[] pagesettings;
     private Date lastupdateddate;

    public AspnetPersonalizationperuser() {
    }

	
    public AspnetPersonalizationperuser(String id, byte[] pagesettings, Date lastupdateddate) {
        this.id = id;
        this.pagesettings = pagesettings;
        this.lastupdateddate = lastupdateddate;
    }
    public AspnetPersonalizationperuser(String id, AspnetPaths aspnetPaths, AspnetUsers aspnetUsers, byte[] pagesettings, Date lastupdateddate) {
       this.id = id;
       this.aspnetPaths = aspnetPaths;
       this.aspnetUsers = aspnetUsers;
       this.pagesettings = pagesettings;
       this.lastupdateddate = lastupdateddate;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pathid")
    public AspnetPaths getAspnetPaths() {
        return this.aspnetPaths;
    }
    
    public void setAspnetPaths(AspnetPaths aspnetPaths) {
        this.aspnetPaths = aspnetPaths;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid")
    public AspnetUsers getAspnetUsers() {
        return this.aspnetUsers;
    }
    
    public void setAspnetUsers(AspnetUsers aspnetUsers) {
        this.aspnetUsers = aspnetUsers;
    }
    
    @Column(name="pagesettings", nullable=false)
    public byte[] getPagesettings() {
        return this.pagesettings;
    }
    
    public void setPagesettings(byte[] pagesettings) {
        this.pagesettings = pagesettings;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastupdateddate", nullable=false, length=29)
    public Date getLastupdateddate() {
        return this.lastupdateddate;
    }
    
    public void setLastupdateddate(Date lastupdateddate) {
        this.lastupdateddate = lastupdateddate;
    }




}


