package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AspnetPersonalizationallusers generated by hbm2java
 */
@Entity
@Table(name="aspnet_personalizationallusers"
    ,schema="public"
)
public class AspnetPersonalizationallusers  implements java.io.Serializable {


     private byte[] pathid;
     private AspnetPaths aspnetPaths;
     private byte[] pagesettings;
     private Date lastupdateddate;

    public AspnetPersonalizationallusers() {
    }

    public AspnetPersonalizationallusers(byte[] pathid, AspnetPaths aspnetPaths, byte[] pagesettings, Date lastupdateddate) {
       this.pathid = pathid;
       this.aspnetPaths = aspnetPaths;
       this.pagesettings = pagesettings;
       this.lastupdateddate = lastupdateddate;
    }
   
     @Id 
    
    @Column(name="pathid", unique=true, nullable=false)
    public byte[] getPathid() {
        return this.pathid;
    }
    
    public void setPathid(byte[] pathid) {
        this.pathid = pathid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pathid", unique=true, nullable=false, insertable=false, updatable=false)
    public AspnetPaths getAspnetPaths() {
        return this.aspnetPaths;
    }
    
    public void setAspnetPaths(AspnetPaths aspnetPaths) {
        this.aspnetPaths = aspnetPaths;
    }
    
    @Column(name="pagesettings", nullable=false)
    public byte[] getPagesettings() {
        return this.pagesettings;
    }
    
    public void setPagesettings(byte[] pagesettings) {
        this.pagesettings = pagesettings;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastupdateddate", nullable=false, length=29)
    public Date getLastupdateddate() {
        return this.lastupdateddate;
    }
    
    public void setLastupdateddate(Date lastupdateddate) {
        this.lastupdateddate = lastupdateddate;
    }




}


