package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AspnetRoles generated by hbm2java
 */
@Entity
@Table(name="aspnet_roles"
    ,schema="public"
)
public class AspnetRoles  implements Serializable {


     private String roleid;
     private AspnetApplications aspnetApplications;
     private String rolename;
     private String loweredrolename;
     private String description;
     private Set<AspnetUsers> aspnetUserses = new HashSet<AspnetUsers>(0);

    public AspnetRoles() {
    }

	
    public AspnetRoles(String roleid, AspnetApplications aspnetApplications, String rolename, String loweredrolename) {
        this.roleid = roleid;
        this.aspnetApplications = aspnetApplications;
        this.rolename = rolename;
        this.loweredrolename = loweredrolename;
    }
    public AspnetRoles(String roleid, AspnetApplications aspnetApplications, String rolename, String loweredrolename, String description, Set<AspnetUsers> aspnetUserses) {
       this.roleid = roleid;
       this.aspnetApplications = aspnetApplications;
       this.rolename = rolename;
       this.loweredrolename = loweredrolename;
       this.description = description;
       this.aspnetUserses = aspnetUserses;
    }
   
     @Id 
    
    @Column(name="roleid", unique=true, nullable=false)
    public String getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="applicationid", nullable=false)
    public AspnetApplications getAspnetApplications() {
        return this.aspnetApplications;
    }
    
    public void setAspnetApplications(AspnetApplications aspnetApplications) {
        this.aspnetApplications = aspnetApplications;
    }
    
    @Column(name="rolename", nullable=false, length=256)
    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    
    @Column(name="loweredrolename", nullable=false, length=256)
    public String getLoweredrolename() {
        return this.loweredrolename;
    }
    
    public void setLoweredrolename(String loweredrolename) {
        this.loweredrolename = loweredrolename;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="aspnetRoleses")
    public Set<AspnetUsers> getAspnetUserses() {
        return this.aspnetUserses;
    }
    
    public void setAspnetUserses(Set<AspnetUsers> aspnetUserses) {
        this.aspnetUserses = aspnetUserses;
    }




}


