package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AspnetSchemaversionsId generated by hbm2java
 */
@Embeddable
public class AspnetSchemaversionsId  implements java.io.Serializable {


     private String feature;
     private String compatibleschemaversion;

    public AspnetSchemaversionsId() {
    }

    public AspnetSchemaversionsId(String feature, String compatibleschemaversion) {
       this.feature = feature;
       this.compatibleschemaversion = compatibleschemaversion;
    }
   

    @Column(name="feature", nullable=false, length=128)
    public String getFeature() {
        return this.feature;
    }
    
    public void setFeature(String feature) {
        this.feature = feature;
    }

    @Column(name="compatibleschemaversion", nullable=false, length=128)
    public String getCompatibleschemaversion() {
        return this.compatibleschemaversion;
    }
    
    public void setCompatibleschemaversion(String compatibleschemaversion) {
        this.compatibleschemaversion = compatibleschemaversion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AspnetSchemaversionsId) ) return false;
		 AspnetSchemaversionsId castOther = ( AspnetSchemaversionsId ) other; 
         
		 return ( (this.getFeature()==castOther.getFeature()) || ( this.getFeature()!=null && castOther.getFeature()!=null && this.getFeature().equals(castOther.getFeature()) ) )
 && ( (this.getCompatibleschemaversion()==castOther.getCompatibleschemaversion()) || ( this.getCompatibleschemaversion()!=null && castOther.getCompatibleschemaversion()!=null && this.getCompatibleschemaversion().equals(castOther.getCompatibleschemaversion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFeature() == null ? 0 : this.getFeature().hashCode() );
         result = 37 * result + ( getCompatibleschemaversion() == null ? 0 : this.getCompatibleschemaversion().hashCode() );
         return result;
   }   


}


