package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA



import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AspnetMembership generated by hbm2java
 */
@Entity
@Table(name="aspnet_membership"
    ,schema="public"
)
public class AspnetMembership  implements Serializable {


     private String userid;
     private AspnetApplications aspnetApplications;
     private AspnetUsers aspnetUsers;
     private String password;
     private int passwordformat;
     private String passwordsalt;
     private String mobilepin;
     private String email;
     private String loweredemail;
     private String passwordquestion;
     private String passwordanswer;
     private boolean isapproved;
     private boolean islockedout;
     private Date createdate;
     private Date lastlogindate;
     private Date lastpasswordchangeddate;
     private Date lastlockoutdate;
     private int failedpasswordattemptcount;
     private Date failedpasswordattemptwindowstart;
     private int failedpasswordanswerattemptcount;
     private Date failedpasswordanswerattemptwindowstart;
     private String comment;

    public AspnetMembership() {
    }

	
    public AspnetMembership(String userid, AspnetApplications aspnetApplications, AspnetUsers aspnetUsers, String password, int passwordformat, String passwordsalt, boolean isapproved, boolean islockedout, Date createdate, Date lastlogindate, Date lastpasswordchangeddate, Date lastlockoutdate, int failedpasswordattemptcount, Date failedpasswordattemptwindowstart, int failedpasswordanswerattemptcount, Date failedpasswordanswerattemptwindowstart) {
        this.userid = userid;
        this.aspnetApplications = aspnetApplications;
        this.aspnetUsers = aspnetUsers;
        this.password = password;
        this.passwordformat = passwordformat;
        this.passwordsalt = passwordsalt;
        this.isapproved = isapproved;
        this.islockedout = islockedout;
        this.createdate = createdate;
        this.lastlogindate = lastlogindate;
        this.lastpasswordchangeddate = lastpasswordchangeddate;
        this.lastlockoutdate = lastlockoutdate;
        this.failedpasswordattemptcount = failedpasswordattemptcount;
        this.failedpasswordattemptwindowstart = failedpasswordattemptwindowstart;
        this.failedpasswordanswerattemptcount = failedpasswordanswerattemptcount;
        this.failedpasswordanswerattemptwindowstart = failedpasswordanswerattemptwindowstart;
    }
    public AspnetMembership(String userid, AspnetApplications aspnetApplications, AspnetUsers aspnetUsers, String password, int passwordformat, String passwordsalt, String mobilepin, String email, String loweredemail, String passwordquestion, String passwordanswer, boolean isapproved, boolean islockedout, Date createdate, Date lastlogindate, Date lastpasswordchangeddate, Date lastlockoutdate, int failedpasswordattemptcount, Date failedpasswordattemptwindowstart, int failedpasswordanswerattemptcount, Date failedpasswordanswerattemptwindowstart, String comment) {
       this.userid = userid;
       this.aspnetApplications = aspnetApplications;
       this.aspnetUsers = aspnetUsers;
       this.password = password;
       this.passwordformat = passwordformat;
       this.passwordsalt = passwordsalt;
       this.mobilepin = mobilepin;
       this.email = email;
       this.loweredemail = loweredemail;
       this.passwordquestion = passwordquestion;
       this.passwordanswer = passwordanswer;
       this.isapproved = isapproved;
       this.islockedout = islockedout;
       this.createdate = createdate;
       this.lastlogindate = lastlogindate;
       this.lastpasswordchangeddate = lastpasswordchangeddate;
       this.lastlockoutdate = lastlockoutdate;
       this.failedpasswordattemptcount = failedpasswordattemptcount;
       this.failedpasswordattemptwindowstart = failedpasswordattemptwindowstart;
       this.failedpasswordanswerattemptcount = failedpasswordanswerattemptcount;
       this.failedpasswordanswerattemptwindowstart = failedpasswordanswerattemptwindowstart;
       this.comment = comment;
    }
   
     @Id 
    
    @Column(name="userid", unique=true, nullable=false)
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="applicationid", nullable=false)
    public AspnetApplications getAspnetApplications() {
        return this.aspnetApplications;
    }
    
    public void setAspnetApplications(AspnetApplications aspnetApplications) {
        this.aspnetApplications = aspnetApplications;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid", unique=true, nullable=false, insertable=false, updatable=false)
    public AspnetUsers getAspnetUsers() {
        return this.aspnetUsers;
    }
    
    public void setAspnetUsers(AspnetUsers aspnetUsers) {
        this.aspnetUsers = aspnetUsers;
    }
    
    @Column(name="password", nullable=false, length=128)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="passwordformat", nullable=false)
    public int getPasswordformat() {
        return this.passwordformat;
    }
    
    public void setPasswordformat(int passwordformat) {
        this.passwordformat = passwordformat;
    }
    
    @Column(name="passwordsalt", nullable=false, length=128)
    public String getPasswordsalt() {
        return this.passwordsalt;
    }
    
    public void setPasswordsalt(String passwordsalt) {
        this.passwordsalt = passwordsalt;
    }
    
    @Column(name="mobilepin", length=16)
    public String getMobilepin() {
        return this.mobilepin;
    }
    
    public void setMobilepin(String mobilepin) {
        this.mobilepin = mobilepin;
    }
    
    @Column(name="email", length=256)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="loweredemail", length=256)
    public String getLoweredemail() {
        return this.loweredemail;
    }
    
    public void setLoweredemail(String loweredemail) {
        this.loweredemail = loweredemail;
    }
    
    @Column(name="passwordquestion", length=256)
    public String getPasswordquestion() {
        return this.passwordquestion;
    }
    
    public void setPasswordquestion(String passwordquestion) {
        this.passwordquestion = passwordquestion;
    }
    
    @Column(name="passwordanswer", length=128)
    public String getPasswordanswer() {
        return this.passwordanswer;
    }
    
    public void setPasswordanswer(String passwordanswer) {
        this.passwordanswer = passwordanswer;
    }
    
    @Column(name="isapproved", nullable=false)
    public boolean isIsapproved() {
        return this.isapproved;
    }
    
    public void setIsapproved(boolean isapproved) {
        this.isapproved = isapproved;
    }
    
    @Column(name="islockedout", nullable=false)
    public boolean isIslockedout() {
        return this.islockedout;
    }
    
    public void setIslockedout(boolean islockedout) {
        this.islockedout = islockedout;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdate", nullable=false, length=29)
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastlogindate", nullable=false, length=29)
    public Date getLastlogindate() {
        return this.lastlogindate;
    }
    
    public void setLastlogindate(Date lastlogindate) {
        this.lastlogindate = lastlogindate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastpasswordchangeddate", nullable=false, length=29)
    public Date getLastpasswordchangeddate() {
        return this.lastpasswordchangeddate;
    }
    
    public void setLastpasswordchangeddate(Date lastpasswordchangeddate) {
        this.lastpasswordchangeddate = lastpasswordchangeddate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastlockoutdate", nullable=false, length=29)
    public Date getLastlockoutdate() {
        return this.lastlockoutdate;
    }
    
    public void setLastlockoutdate(Date lastlockoutdate) {
        this.lastlockoutdate = lastlockoutdate;
    }
    
    @Column(name="failedpasswordattemptcount", nullable=false)
    public int getFailedpasswordattemptcount() {
        return this.failedpasswordattemptcount;
    }
    
    public void setFailedpasswordattemptcount(int failedpasswordattemptcount) {
        this.failedpasswordattemptcount = failedpasswordattemptcount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="failedpasswordattemptwindowstart", nullable=false, length=29)
    public Date getFailedpasswordattemptwindowstart() {
        return this.failedpasswordattemptwindowstart;
    }
    
    public void setFailedpasswordattemptwindowstart(Date failedpasswordattemptwindowstart) {
        this.failedpasswordattemptwindowstart = failedpasswordattemptwindowstart;
    }
    
    @Column(name="failedpasswordanswerattemptcount", nullable=false)
    public int getFailedpasswordanswerattemptcount() {
        return this.failedpasswordanswerattemptcount;
    }
    
    public void setFailedpasswordanswerattemptcount(int failedpasswordanswerattemptcount) {
        this.failedpasswordanswerattemptcount = failedpasswordanswerattemptcount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="failedpasswordanswerattemptwindowstart", nullable=false, length=29)
    public Date getFailedpasswordanswerattemptwindowstart() {
        return this.failedpasswordanswerattemptwindowstart;
    }
    
    public void setFailedpasswordanswerattemptwindowstart(Date failedpasswordanswerattemptwindowstart) {
        this.failedpasswordanswerattemptwindowstart = failedpasswordanswerattemptwindowstart;
    }
    
    @Column(name="comment")
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


