package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AspnetProfile generated by hbm2java
 */
@Entity
@Table(name="aspnet_profile"
    ,schema="public"
)
public class AspnetProfile  implements Serializable {


     private String userid;
     private AspnetUsers aspnetUsers;
     private String propertynames;
     private String propertyvaluesstring;
     private byte[] propertyvaluesbinary;
     private Date lastupdateddate;

    public AspnetProfile() {
    }

    public AspnetProfile(String userid, AspnetUsers aspnetUsers, String propertynames, String propertyvaluesstring, byte[] propertyvaluesbinary, Date lastupdateddate) {
       this.userid = userid;
       this.aspnetUsers = aspnetUsers;
       this.propertynames = propertynames;
       this.propertyvaluesstring = propertyvaluesstring;
       this.propertyvaluesbinary = propertyvaluesbinary;
       this.lastupdateddate = lastupdateddate;
    }
   
     @Id 
    
    @Column(name="userid", unique=true, nullable=false)
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid", unique=true, nullable=false, insertable=false, updatable=false)
    public AspnetUsers getAspnetUsers() {
        return this.aspnetUsers;
    }
    
    public void setAspnetUsers(AspnetUsers aspnetUsers) {
        this.aspnetUsers = aspnetUsers;
    }
    
    @Column(name="propertynames", nullable=false)
    public String getPropertynames() {
        return this.propertynames;
    }
    
    public void setPropertynames(String propertynames) {
        this.propertynames = propertynames;
    }
    
    @Column(name="propertyvaluesstring", nullable=false)
    public String getPropertyvaluesstring() {
        return this.propertyvaluesstring;
    }
    
    public void setPropertyvaluesstring(String propertyvaluesstring) {
        this.propertyvaluesstring = propertyvaluesstring;
    }
    
    @Column(name="propertyvaluesbinary", nullable=false)
    public byte[] getPropertyvaluesbinary() {
        return this.propertyvaluesbinary;
    }
    
    public void setPropertyvaluesbinary(byte[] propertyvaluesbinary) {
        this.propertyvaluesbinary = propertyvaluesbinary;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastupdateddate", nullable=false, length=29)
    public Date getLastupdateddate() {
        return this.lastupdateddate;
    }
    
    public void setLastupdateddate(Date lastupdateddate) {
        this.lastupdateddate = lastupdateddate;
    }




}


