package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblactions generated by hbm2java
 */
@Entity
@Table(name="tblactions"
    ,schema="public"
)
public class Tblactions  implements java.io.Serializable {


     private int actionid;
     private String actionname;
     private Set<Tblbanneractions> tblbanneractionses = new HashSet<Tblbanneractions>(0);

    public Tblactions() {
    }

	
    public Tblactions(int actionid) {
        this.actionid = actionid;
    }
    public Tblactions(int actionid, String actionname, Set<Tblbanneractions> tblbanneractionses) {
       this.actionid = actionid;
       this.actionname = actionname;
       this.tblbanneractionses = tblbanneractionses;
    }
   
     @Id 
    
    @Column(name="actionid", unique=true, nullable=false)
    public int getActionid() {
        return this.actionid;
    }
    
    public void setActionid(int actionid) {
        this.actionid = actionid;
    }
    
    @Column(name="actionname", length=30)
    public String getActionname() {
        return this.actionname;
    }
    
    public void setActionname(String actionname) {
        this.actionname = actionname;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblactions")
    public Set<Tblbanneractions> getTblbanneractionses() {
        return this.tblbanneractionses;
    }
    
    public void setTblbanneractionses(Set<Tblbanneractions> tblbanneractionses) {
        this.tblbanneractionses = tblbanneractionses;
    }




}


