package com.sdk.service;


// Generated Feb 12, 2014 7:18:03 PM by Hibernate Tools 3.2.1.GA



/**
 * TblAdvRefTemp generated by hbm2java
 */
public class TblAdvRefTemp  implements Comparable<TblAdvRefTemp> {


     private TblAdvRefTempId id;

    public TblAdvRefTemp() {
    }

    public TblAdvRefTemp(TblAdvRefTempId id) {
       this.id = id;
    }
   
    public TblAdvRefTempId getId() {
        return this.id;
    }
    
    public void setId(TblAdvRefTempId id) {
        this.id = id;
    }


	@Override
	public int compareTo(TblAdvRefTemp o) {
		 if (this.id.getDistance() == o.id.getDistance())
	            return 0;
	        else if (this.id.getDistance() > o.id.getDistance())
	            return 1;
	        else
	            return -1;
	}

	




}


