package com.sdk.service;
// Generated Feb 12, 2014 7:18:03 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TblAdvRefTempId generated by hbm2java
 */
public class TblAdvRefTempId   {


     private String advReferenceId;
     private String bannerId;
     private Double distance;
     private Integer priority;
     private String advRefId;
     private BigDecimal eventMillis;
     private String locationId;
     private Integer geomaxradius;

    public TblAdvRefTempId() {
    }

	public TblAdvRefTempId(String advReferenceId, String bannerId,
			Double distance, Integer priority, String advRefId,
			BigDecimal eventMillis, String locationId, Integer geomaxradius) {
		super();
		this.advReferenceId = advReferenceId;
		this.bannerId = bannerId;
		this.distance = distance;
		this.priority = priority;
		this.advRefId = advRefId;
		this.eventMillis = eventMillis;
		this.locationId = locationId;
		this.geomaxradius = geomaxradius;
	}

	/**
	 * @return the advReferenceId
	 */
	public String getAdvReferenceId() {
		return advReferenceId;
	}

	/**
	 * @param advReferenceId the advReferenceId to set
	 */
	public void setAdvReferenceId(String advReferenceId) {
		this.advReferenceId = advReferenceId;
	}

	/**
	 * @return the bannerId
	 */
	public String getBannerId() {
		return bannerId;
	}

	/**
	 * @param bannerId the bannerId to set
	 */
	public void setBannerId(String bannerId) {
		this.bannerId = bannerId;
	}

	/**
	 * @return the distance
	 */
	public Double getDistance() {
		return distance;
	}

	/**
	 * @param distance the distance to set
	 */
	public void setDistance(Double distance) {
		this.distance = distance;
	}

	/**
	 * @return the priority
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * @param priority the priority to set
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * @return the advRefId
	 */
	public String getAdvRefId() {
		return advRefId;
	}

	/**
	 * @param advRefId the advRefId to set
	 */
	public void setAdvRefId(String advRefId) {
		this.advRefId = advRefId;
	}

	/**
	 * @return the eventMillis
	 */
	public BigDecimal getEventMillis() {
		return eventMillis;
	}

	/**
	 * @param eventMillis the eventMillis to set
	 */
	public void setEventMillis(BigDecimal eventMillis) {
		this.eventMillis = eventMillis;
	}

	/**
	 * @return the locationId
	 */
	public String getLocationId() {
		return locationId;
	}

	/**
	 * @param locationId the locationId to set
	 */
	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	/**
	 * @return the geomaxradius
	 */
	public Integer getGeomaxradius() {
		return geomaxradius;
	}

	/**
	 * @param geomaxradius the geomaxradius to set
	 */
	public void setGeomaxradius(Integer geomaxradius) {
		this.geomaxradius = geomaxradius;
	}

	
   


}


