package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblbannerimages generated by hbm2java
 */
@Entity
@Table(name="tblbannerimages"
    ,schema="public"
)
public class Tblbannerimages  implements Serializable {


     private String imageid;
     private Tblbannersizes tblbannersizes;
     private Tblbanners tblbanners;
     private byte[] image;
     private String contenttype;
     private String filename;
     private Date datecreated;

    public Tblbannerimages() {
    }

	
    public Tblbannerimages(String imageid) {
        this.imageid = imageid;
    }
    public Tblbannerimages(String imageid, Tblbannersizes tblbannersizes, Tblbanners tblbanners, byte[] image, String contenttype, String filename, Date datecreated) {
       this.imageid = imageid;
       this.tblbannersizes = tblbannersizes;
       this.tblbanners = tblbanners;
       this.image = image;
       this.contenttype = contenttype;
       this.filename = filename;
       this.datecreated = datecreated;
    }
   
     @Id 
    
    @Column(name="imageid", unique=true, nullable=false)
    public String getImageid() {
        return this.imageid;
    }
    
    public void setImageid(String imageid) {
        this.imageid = imageid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bannersizeid")
    public Tblbannersizes getTblbannersizes() {
        return this.tblbannersizes;
    }
    
    public void setTblbannersizes(Tblbannersizes tblbannersizes) {
        this.tblbannersizes = tblbannersizes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bannerid")
    public Tblbanners getTblbanners() {
        return this.tblbanners;
    }
    
    public void setTblbanners(Tblbanners tblbanners) {
        this.tblbanners = tblbanners;
    }
    
    @Column(name="image")
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    
    @Column(name="contenttype", length=30)
    public String getContenttype() {
        return this.contenttype;
    }
    
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype;
    }
    
    @Column(name="filename", length=50)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datecreated", length=29)
    public Date getDatecreated() {
        return this.datecreated;
    }
    
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }




}


