package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblbannerlocations generated by hbm2java
 */
@Entity
@Table(name="tblbannerlocations"
    ,schema="public"
)
public class Tblbannerlocations  implements java.io.Serializable {


     private TblbannerlocationsId id;
     private Tblbanners tblbanners;
     private Tbllocations tbllocations;
     private int geomaxradius;

    public Tblbannerlocations() {
    }

    public Tblbannerlocations(TblbannerlocationsId id, Tblbanners tblbanners, Tbllocations tbllocations, int geomaxradius) {
       this.id = id;
       this.tblbanners = tblbanners;
       this.tbllocations = tbllocations;
       this.geomaxradius = geomaxradius;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="bannerid", column=@Column(name="bannerid", nullable=false) ), 
        @AttributeOverride(name="locationid", column=@Column(name="locationid", nullable=false) ) } )
    public TblbannerlocationsId getId() {
        return this.id;
    }
    
    public void setId(TblbannerlocationsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bannerid", nullable=false, insertable=false, updatable=false)
    public Tblbanners getTblbanners() {
        return this.tblbanners;
    }
    
    public void setTblbanners(Tblbanners tblbanners) {
        this.tblbanners = tblbanners;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="locationid", nullable=false, insertable=false, updatable=false)
    public Tbllocations getTbllocations() {
        return this.tbllocations;
    }
    
    public void setTbllocations(Tbllocations tbllocations) {
        this.tbllocations = tbllocations;
    }
    
    @Column(name="geomaxradius", nullable=false)
    public int getGeomaxradius() {
        return this.geomaxradius;
    }
    
    public void setGeomaxradius(int geomaxradius) {
        this.geomaxradius = geomaxradius;
    }




}


