package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblbannerhandsets generated by hbm2java
 */
@Entity
@Table(name="tblbannerhandsets"
    ,schema="public"
)
public class Tblbannerhandsets  implements Serializable {


     private String banhansetid;
     private Tblhandset tblhandset;
     private Tblbanners tblbanners;

    public Tblbannerhandsets() {
    }

	
    public Tblbannerhandsets(String banhansetid) {
        this.banhansetid = banhansetid;
    }
    public Tblbannerhandsets(String banhansetid, Tblhandset tblhandset, Tblbanners tblbanners) {
       this.banhansetid = banhansetid;
       this.tblhandset = tblhandset;
       this.tblbanners = tblbanners;
    }
   
     @Id 
    
    @Column(name="banhansetid", unique=true, nullable=false)
    public String getBanhansetid() {
        return this.banhansetid;
    }
    
    public void setBanhansetid(String banhansetid) {
        this.banhansetid = banhansetid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="handsetid")
    public Tblhandset getTblhandset() {
        return this.tblhandset;
    }
    
    public void setTblhandset(Tblhandset tblhandset) {
        this.tblhandset = tblhandset;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bannerid")
    public Tblbanners getTblbanners() {
        return this.tblbanners;
    }
    
    public void setTblbanners(Tblbanners tblbanners) {
        this.tblbanners = tblbanners;
    }




}


