package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblbannersubcateories generated by hbm2java
 */
@Entity
@Table(name="tblbannersubcateories"
    ,schema="public"
)
public class Tblbannersubcateories  implements Serializable {


     private String bancatlink;
     private Tblsyssubcategories tblsyssubcategories;
     private Tblbanners tblbanners;

    public Tblbannersubcateories() {
    }

    public Tblbannersubcateories(String bancatlink, Tblsyssubcategories tblsyssubcategories, Tblbanners tblbanners) {
       this.bancatlink = bancatlink;
       this.tblsyssubcategories = tblsyssubcategories;
       this.tblbanners = tblbanners;
    }
   
     @Id 
    
    @Column(name="bancatlink", unique=true, nullable=false)
    public String getBancatlink() {
        return this.bancatlink;
    }
    
    public void setBancatlink(String bancatlink) {
        this.bancatlink = bancatlink;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subcategoryid", nullable=false)
    public Tblsyssubcategories getTblsyssubcategories() {
        return this.tblsyssubcategories;
    }
    
    public void setTblsyssubcategories(Tblsyssubcategories tblsyssubcategories) {
        this.tblsyssubcategories = tblsyssubcategories;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bannerid", nullable=false)
    public Tblbanners getTblbanners() {
        return this.tblbanners;
    }
    
    public void setTblbanners(Tblbanners tblbanners) {
        this.tblbanners = tblbanners;
    }




}


