package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblbannerdayofweeks generated by hbm2java
 */
@Entity
@Table(name="tblbannerdayofweeks"
    ,schema="public"
)
public class Tblbannerdayofweeks  implements Serializable {


     private String dayofweekid;
     private String bannerid;
     private int dayofweek;

    public Tblbannerdayofweeks() {
    }

    public Tblbannerdayofweeks(String dayofweekid, String bannerid, int dayofweek) {
       this.dayofweekid = dayofweekid;
       this.bannerid = bannerid;
       this.dayofweek = dayofweek;
    }
   
     @Id 
    
    @Column(name="dayofweekid", unique=true, nullable=false)
    public String getDayofweekid() {
        return this.dayofweekid;
    }
    
    public void setDayofweekid(String dayofweekid) {
        this.dayofweekid = dayofweekid;
    }
    
    @Column(name="bannerid", nullable=false)
    public String getBannerid() {
        return this.bannerid;
    }
    
    public void setBannerid(String bannerid) {
        this.bannerid = bannerid;
    }
    
    @Column(name="dayofweek", nullable=false)
    public int getDayofweek() {
        return this.dayofweek;
    }
    
    public void setDayofweek(int dayofweek) {
        this.dayofweek = dayofweek;
    }




}


