package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblbannertimes generated by hbm2java
 */
@Entity
@Table(name="tblbannertimes"
    ,schema="public"
)
public class Tblbannertimes  implements Serializable {


     private String timeid;
     private Tblbanners tblbanners;
     private Date starttime;
     private Date endtime;

    public Tblbannertimes() {
    }

	
    public Tblbannertimes(String timeid, Tblbanners tblbanners) {
        this.timeid = timeid;
        this.tblbanners = tblbanners;
    }
    public Tblbannertimes(String timeid, Tblbanners tblbanners, Date starttime, Date endtime) {
       this.timeid = timeid;
       this.tblbanners = tblbanners;
       this.starttime = starttime;
       this.endtime = endtime;
    }
   
     @Id 
    
    @Column(name="timeid", unique=true, nullable=false)
    public String getTimeid() {
        return this.timeid;
    }
    
    public void setTimeid(String timeid) {
        this.timeid = timeid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bannerid", nullable=false)
    public Tblbanners getTblbanners() {
        return this.tblbanners;
    }
    
    public void setTblbanners(Tblbanners tblbanners) {
        this.tblbanners = tblbanners;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="starttime", length=29)
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="endtime", length=29)
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }




}


