

package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA



import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblbannerlogs generated by hbm2java
 */
@Entity
@Table(name="tblbannerlogs"
    ,schema="public"
)
public class Tblbannerlogs  implements Serializable {


     private String logid;
     private Tblbanners tblbanners;
     private Tbllocations tbllocations;
     private Date datehour;
     private Long impressions=new Long(0);
     private Long clicks=new Long(0);
     private Long convertions=new Long(0);
     private Long call=new Long(0);
     private Long web=new Long(0);
     private Long coupon=new Long(0);
     private Long driveto=new Long(0);
     private Long walkto=new Long(0);
     private Long showonmap=new Long(0);
     private Integer companyid;

    public Tblbannerlogs() {
    }

	
    public Tblbannerlogs(String logid) {
        this.logid = logid;
    }
    public Tblbannerlogs(String logid, Tblbanners tblbanners, Tbllocations tbllocations, Date datehour, Long impressions, Long clicks, Long convertions, Long call, Long web, Long coupon, Long driveto, Long walkto, Long showonmap, Integer companyid) {
       this.logid = logid;
       this.tblbanners = tblbanners;
       this.tbllocations = tbllocations;
       this.datehour = datehour;
       this.impressions = impressions;
       this.clicks = clicks;
       this.convertions = convertions;
       this.call = call;
       this.web = web;
       this.coupon = coupon;
       this.driveto = driveto;
       this.walkto = walkto;
       this.showonmap = showonmap;
       this.companyid = companyid;
    }
   
    @Id
    @Column(name="logid", unique=true, nullable=false)
     public String getLogid() {
        return this.logid;
    }
    
    public void setLogid(String logid) {
        this.logid = logid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bannerid")
    public Tblbanners getTblbanners() {
        return this.tblbanners;
    }
    
    public void setTblbanners(Tblbanners tblbanners) {
        this.tblbanners = tblbanners;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="locationid")
    public Tbllocations getTbllocations() {
        return this.tbllocations;
    }
    
    public void setTbllocations(Tbllocations tbllocations) {
        this.tbllocations = tbllocations;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datehour", length=29)
    public Date getDatehour() {
        return this.datehour;
    }
    
    public void setDatehour(Date datehour) {
        this.datehour = datehour;
    }
    
    @Column(name="impressions")
    public Long getImpressions() {
        return this.impressions;
    }
    
    public void setImpressions(Long impressions) {
        this.impressions = impressions;
    }
    
    @Column(name="clicks")
    public Long getClicks() {
        return this.clicks;
    }
    
    public void setClicks(Long clicks) {
        this.clicks = clicks;
    }
    
    @Column(name="convertions")
    public Long getConvertions() {
        return this.convertions;
    }
    
    public void setConvertions(Long convertions) {
        this.convertions = convertions;
    }
    
    @Column(name="call")
    public Long getCall() {
        return this.call;
    }
    
    public void setCall(Long call) {
        this.call = call;
    }
    
    @Column(name="web")
    public Long getWeb() {
        return this.web;
    }
    
    public void setWeb(Long web) {
        this.web = web;
    }
    
    @Column(name="coupon")
    public Long getCoupon() {
        return this.coupon;
    }
    
    public void setCoupon(Long coupon) {
        this.coupon = coupon;
    }
    
    @Column(name="driveto")
    public Long getDriveto() {
        return this.driveto;
    }
    
    public void setDriveto(Long driveto) {
        this.driveto = driveto;
    }
    
    @Column(name="walkto")
    public Long getWalkto() {
        return this.walkto;
    }
    
    public void setWalkto(Long walkto) {
        this.walkto = walkto;
    }
    
    @Column(name="showonmap")
    public Long getShowonmap() {
        return this.showonmap;
    }
    
    public void setShowonmap(Long showonmap) {
        this.showonmap = showonmap;
    }
    
    @Column(name="companyid")
    public Integer getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }




}


