package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblbanners generated by hbm2java
 */
@Entity
@Table(name="tblbanners"
    ,schema="public"
)
public class Tblbanners  implements Serializable {


     private UUID bannerid;
     private Tblsyscategories tblsyscategories;
     private Tblsysbrands tblsysbrands;
     private Boolean catexclusive;
     private Integer subcategoryid;
     private Boolean exclusive;
     private String bannername;
     private Integer statusid;
     private String campaigntype;
     private Date startdate;
     private Date enddate;
     private Double budget;
     private Double dailybudget;
     private Double curdailybudget;
     private Date dailybudgetdate;
     private Double balance;
     private Double cpm;
     private Double cpc;
     private Double cpa;
     private Double cpmlimit;
     private Double cpclimit;
     private Double cpalimit;
     private Long impressions=new Long(0);
     private Long clicks=new Long(0);
     private Long convertions=new Long(0);
     private Integer priority;
     private String keywords;
     private String url;
     private Boolean enabled;
     private Date datecreated;
     private Boolean archived;
     private Date datearchived;
     private Set<Tblbannerimages> tblbannerimageses = new HashSet<Tblbannerimages>(0);
     private Set<Tblbannerlogs> tblbannerlogses = new HashSet<Tblbannerlogs>(0);
     private Set<Tblbannerhandsets> tblbannerhandsetses = new HashSet<Tblbannerhandsets>(0);
     private Set<Tblbannersubcateories> tblbannersubcateorieses = new HashSet<Tblbannersubcateories>(0);
     private Set<Tblbannertimes> tblbannertimeses = new HashSet<Tblbannertimes>(0);
     private Set<Tblbannerlocations> tblbannerlocationses = new HashSet<Tblbannerlocations>(0);
     private Set<Tblbanneractions> tblbanneractionses = new HashSet<Tblbanneractions>(0);

    public Tblbanners() {
    }

	
    public Tblbanners(UUID bannerid, Tblsysbrands tblsysbrands) {
        this.bannerid = bannerid;
        this.tblsysbrands = tblsysbrands;
    }
    public Tblbanners(UUID bannerid, Tblsyscategories tblsyscategories, Tblsysbrands tblsysbrands, Boolean catexclusive, Integer subcategoryid, Boolean exclusive, String bannername, Integer statusid, String campaigntype, Date startdate, Date enddate, Double budget, Double dailybudget, Double curdailybudget, Date dailybudgetdate, Double balance, Double cpm, Double cpc, Double cpa, Double cpmlimit, Double cpclimit, Double cpalimit, Long impressions, Long clicks, Long convertions, Integer priority, String keywords, String url, Boolean enabled, Date datecreated, Boolean archived, Date datearchived, Set<Tblbannerimages> tblbannerimageses, Set<Tblbannerlogs> tblbannerlogses, Set<Tblbannerhandsets> tblbannerhandsetses, Set<Tblbannersubcateories> tblbannersubcateorieses, Set<Tblbannertimes> tblbannertimeses, Set<Tblbannerlocations> tblbannerlocationses, Set<Tblbanneractions> tblbanneractionses) {
       this.bannerid = bannerid;
       this.tblsyscategories = tblsyscategories;
       this.tblsysbrands = tblsysbrands;
       this.catexclusive = catexclusive;
       this.subcategoryid = subcategoryid;
       this.exclusive = exclusive;
       this.bannername = bannername;
       this.statusid = statusid;
       this.campaigntype = campaigntype;
       this.startdate = startdate;
       this.enddate = enddate;
       this.budget = budget;
       this.dailybudget = dailybudget;
       this.curdailybudget = curdailybudget;
       this.dailybudgetdate = dailybudgetdate;
       this.balance = balance;
       this.cpm = cpm;
       this.cpc = cpc;
       this.cpa = cpa;
       this.cpmlimit = cpmlimit;
       this.cpclimit = cpclimit;
       this.cpalimit = cpalimit;
       this.impressions = impressions;
       this.clicks = clicks;
       this.convertions = convertions;
       this.priority = priority;
       this.keywords = keywords;
       this.url = url;
       this.enabled = enabled;
       this.datecreated = datecreated;
       this.archived = archived;
       this.datearchived = datearchived;
       this.tblbannerimageses = tblbannerimageses;
       this.tblbannerlogses = tblbannerlogses;
       this.tblbannerhandsetses = tblbannerhandsetses;
       this.tblbannersubcateorieses = tblbannersubcateorieses;
       this.tblbannertimeses = tblbannertimeses;
       this.tblbannerlocationses = tblbannerlocationses;
       this.tblbanneractionses = tblbanneractionses;
    }
   
     @Id 
   
    @Column(name="bannerid", unique=true, nullable=false,columnDefinition="uuid")
    public String getBannerid() {
        return this.bannerid.toString();
    }
    
    public void setBannerid(String bannerid) {
        this.bannerid = UUID.fromString(bannerid);
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoryid")
    public Tblsyscategories getTblsyscategories() {
        return this.tblsyscategories;
    }
    
    public void setTblsyscategories(Tblsyscategories tblsyscategories) {
        this.tblsyscategories = tblsyscategories;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brandid", nullable=false)
    public Tblsysbrands getTblsysbrands() {
        return this.tblsysbrands;
    }
    
    public void setTblsysbrands(Tblsysbrands tblsysbrands) {
        this.tblsysbrands = tblsysbrands;
    }
    
    @Column(name="catexclusive")
    public Boolean getCatexclusive() {
        return this.catexclusive;
    }
    
    public void setCatexclusive(Boolean catexclusive) {
        this.catexclusive = catexclusive;
    }
    
    @Column(name="subcategoryid")
    public Integer getSubcategoryid() {
        return this.subcategoryid;
    }
    
    public void setSubcategoryid(Integer subcategoryid) {
        this.subcategoryid = subcategoryid;
    }
    
    @Column(name="exclusive")
    public Boolean getExclusive() {
        return this.exclusive;
    }
    
    public void setExclusive(Boolean exclusive) {
        this.exclusive = exclusive;
    }
    
    @Column(name="bannername", length=100)
    public String getBannername() {
        return this.bannername;
    }
    
    public void setBannername(String bannername) {
        this.bannername = bannername;
    }
    
    @Column(name="statusid")
    public Integer getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }
    
    @Column(name="campaigntype", length=3)
    public String getCampaigntype() {
        return this.campaigntype;
    }
    
    public void setCampaigntype(String campaigntype) {
        this.campaigntype = campaigntype;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="startdate", length=29)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="enddate", length=29)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    
    @Column(name="budget", precision=17, scale=17)
    public Double getBudget() {
        return this.budget;
    }
    
    public void setBudget(Double budget) {
        this.budget = budget;
    }
    
    @Column(name="dailybudget", precision=17, scale=17)
    public Double getDailybudget() {
        return this.dailybudget;
    }
    
    public void setDailybudget(Double dailybudget) {
        this.dailybudget = dailybudget;
    }
    
    @Column(name="curdailybudget", precision=17, scale=17)
    public Double getCurdailybudget() {
        return this.curdailybudget;
    }
    
    public void setCurdailybudget(Double curdailybudget) {
        this.curdailybudget = curdailybudget;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dailybudgetdate", length=13)
    public Date getDailybudgetdate() {
        return this.dailybudgetdate;
    }
    
    public void setDailybudgetdate(Date dailybudgetdate) {
        this.dailybudgetdate = dailybudgetdate;
    }
    
    @Column(name="balance", precision=17, scale=17)
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    
    @Column(name="cpm", precision=17, scale=17)
    public Double getCpm() {
        return this.cpm;
    }
    
    public void setCpm(Double cpm) {
        this.cpm = cpm;
    }
    
    @Column(name="cpc", precision=17, scale=17)
    public Double getCpc() {
        return this.cpc;
    }
    
    public void setCpc(Double cpc) {
        this.cpc = cpc;
    }
    
    @Column(name="cpa", precision=17, scale=17)
    public Double getCpa() {
        return this.cpa;
    }
    
    public void setCpa(Double cpa) {
        this.cpa = cpa;
    }
    
    @Column(name="cpmlimit", precision=17, scale=17)
    public Double getCpmlimit() {
        return this.cpmlimit;
    }
    
    public void setCpmlimit(Double cpmlimit) {
        this.cpmlimit = cpmlimit;
    }
    
    @Column(name="cpclimit", precision=17, scale=17)
    public Double getCpclimit() {
        return this.cpclimit;
    }
    
    public void setCpclimit(Double cpclimit) {
        this.cpclimit = cpclimit;
    }
    
    @Column(name="cpalimit", precision=17, scale=17)
    public Double getCpalimit() {
        return this.cpalimit;
    }
    
    public void setCpalimit(Double cpalimit) {
        this.cpalimit = cpalimit;
    }
    
    @Column(name="impressions")
    public Long getImpressions() {
        return this.impressions;
    }
    
    public void setImpressions(Long impressions) {
        this.impressions = impressions;
    }
    
    @Column(name="clicks")
    public Long getClicks() {
        return this.clicks;
    }
    
    public void setClicks(Long clicks) {
        this.clicks = clicks;
    }
    
    @Column(name="convertions")
    public Long getConvertions() {
        return this.convertions;
    }
    
    public void setConvertions(Long convertions) {
        this.convertions = convertions;
    }
    
    @Column(name="priority")
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    
    @Column(name="keywords", length=500)
    public String getKeywords() {
        return this.keywords;
    }
    
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }
    
    @Column(name="url", length=500)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="enabled")
    public Boolean getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datecreated", length=29)
    public Date getDatecreated() {
        return this.datecreated;
    }
    
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }
    
    @Column(name="archived")
    public Boolean getArchived() {
        return this.archived;
    }
    
    public void setArchived(Boolean archived) {
        this.archived = archived;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datearchived", length=29)
    public Date getDatearchived() {
        return this.datearchived;
    }
    
    public void setDatearchived(Date datearchived) {
        this.datearchived = datearchived;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblbanners")
    public Set<Tblbannerimages> getTblbannerimageses() {
        return this.tblbannerimageses;
    }
    
    public void setTblbannerimageses(Set<Tblbannerimages> tblbannerimageses) {
        this.tblbannerimageses = tblbannerimageses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblbanners")
    public Set<Tblbannerlogs> getTblbannerlogses() {
        return this.tblbannerlogses;
    }
    
    public void setTblbannerlogses(Set<Tblbannerlogs> tblbannerlogses) {
        this.tblbannerlogses = tblbannerlogses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblbanners")
    public Set<Tblbannerhandsets> getTblbannerhandsetses() {
        return this.tblbannerhandsetses;
    }
    
    public void setTblbannerhandsetses(Set<Tblbannerhandsets> tblbannerhandsetses) {
        this.tblbannerhandsetses = tblbannerhandsetses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblbanners")
    public Set<Tblbannersubcateories> getTblbannersubcateorieses() {
        return this.tblbannersubcateorieses;
    }
    
    public void setTblbannersubcateorieses(Set<Tblbannersubcateories> tblbannersubcateorieses) {
        this.tblbannersubcateorieses = tblbannersubcateorieses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblbanners")
    public Set<Tblbannertimes> getTblbannertimeses() {
        return this.tblbannertimeses;
    }
    
    public void setTblbannertimeses(Set<Tblbannertimes> tblbannertimeses) {
        this.tblbannertimeses = tblbannertimeses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblbanners")
    public Set<Tblbannerlocations> getTblbannerlocationses() {
        return this.tblbannerlocationses;
    }
    
    public void setTblbannerlocationses(Set<Tblbannerlocations> tblbannerlocationses) {
        this.tblbannerlocationses = tblbannerlocationses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblbanners")
    public Set<Tblbanneractions> getTblbanneractionses() {
        return this.tblbanneractionses;
    }
    
    public void setTblbanneractionses(Set<Tblbanneractions> tblbanneractionses) {
        this.tblbanneractionses = tblbanneractionses;
    }




}


