package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblbannerlocationsId generated by hbm2java
 */
@Embeddable
public class TblbannerlocationsId  implements Serializable {


     private String bannerid;
     private String locationid;

    public TblbannerlocationsId() {
    }

    public TblbannerlocationsId(String bannerid, String locationid) {
       this.bannerid = bannerid;
       this.locationid = locationid;
    }
   

    @Column(name="bannerid", nullable=false)
    public String getBannerid() {
        return this.bannerid;
    }
    
    public void setBannerid(String bannerid) {
        this.bannerid = bannerid;
    }

    @Column(name="locationid", nullable=false)
    public String getLocationid() {
        return this.locationid;
    }
    
    public void setLocationid(String locationid) {
        this.locationid = locationid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblbannerlocationsId) ) return false;
		 TblbannerlocationsId castOther = ( TblbannerlocationsId ) other; 
         
		 return ( (this.getBannerid()==castOther.getBannerid()) || ( this.getBannerid()!=null && castOther.getBannerid()!=null && this.getBannerid().equals(castOther.getBannerid()) ) )
 && ( (this.getLocationid()==castOther.getLocationid()) || ( this.getLocationid()!=null && castOther.getLocationid()!=null && this.getLocationid().equals(castOther.getLocationid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBannerid() == null ? 0 : this.getBannerid().hashCode() );
         result = 37 * result + ( getLocationid() == null ? 0 : this.getLocationid().hashCode() );
         return result;
   }   


}


