package com.sdk.service;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
// Generated Feb 12, 2014 7:18:03 PM by Hibernate Tools 3.2.1.GA


/**
 * TblAdvRefTempId generated by hbm2java
 */

@Entity
@Table(name="tblcompanybanner"
    ,schema="public"
)
public class Tblcompanybanner   {


	 private Integer id;
	 private Integer companyid;
     private String bannerid;


    public Tblcompanybanner() {
    }

    @Id 
    
    @Column(name="id", unique=true, nullable=false)
	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="companyid")
	public Integer getCompanyid() {
		return companyid;
	}


	public void setCompanyid(Integer companyid) {
		this.companyid = companyid;
	}

	@Column(name="bannerid")
	public String getBannerid() {
		return bannerid;
	}


	public void setBannerId(String bannerid) {
		this.bannerid = bannerid;
	}


   


}


