package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblhandset generated by hbm2java
 */
@Entity
@Table(name="tblhandset"
    ,schema="public"
)
public class Tblhandset  implements java.io.Serializable {


     private int handsetid;
     private String handsetname;
     private Set<Tblbannerhandsets> tblbannerhandsetses = new HashSet<Tblbannerhandsets>(0);

    public Tblhandset() {
    }

	
    public Tblhandset(int handsetid) {
        this.handsetid = handsetid;
    }
    public Tblhandset(int handsetid, String handsetname, Set<Tblbannerhandsets> tblbannerhandsetses) {
       this.handsetid = handsetid;
       this.handsetname = handsetname;
       this.tblbannerhandsetses = tblbannerhandsetses;
    }
   
     @Id 
    
    @Column(name="handsetid", unique=true, nullable=false)
    public int getHandsetid() {
        return this.handsetid;
    }
    
    public void setHandsetid(int handsetid) {
        this.handsetid = handsetid;
    }
    
    @Column(name="handsetname", length=50)
    public String getHandsetname() {
        return this.handsetname;
    }
    
    public void setHandsetname(String handsetname) {
        this.handsetname = handsetname;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblhandset")
    public Set<Tblbannerhandsets> getTblbannerhandsetses() {
        return this.tblbannerhandsetses;
    }
    
    public void setTblbannerhandsetses(Set<Tblbannerhandsets> tblbannerhandsetses) {
        this.tblbannerhandsetses = tblbannerhandsetses;
    }




}


