package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbllocations generated by hbm2java
 */
@Entity
@Table(name="tbllocations"
    ,schema="public"
)
public class Tbllocations  implements Serializable {


     private UUID locationid;
     private Tblsysbrands tblsysbrands;
     private String locationname;
     private String storecode;
     private String storename;
     private String addressline1;
     private String addressline2;
     private String city;
     private String postalcode;
     private String countrycode;
     private String mainphone;
     private String homepage;
     private Double latitude;
     private Double longitude;
     private Integer locationmaxradius;
     private Boolean approved;
     private Set<Tblbannerlogs> tblbannerlogses = new HashSet<Tblbannerlogs>(0);
     private Set<Tblbannerlocations> tblbannerlocationses = new HashSet<Tblbannerlocations>(0);

    public Tbllocations() {
    }

	
    public Tbllocations(UUID locationid, Tblsysbrands tblsysbrands, String locationname, String storecode) {
        this.locationid = locationid;
        this.tblsysbrands = tblsysbrands;
        this.locationname = locationname;
        this.storecode = storecode;
    }
    public Tbllocations(UUID locationid, Tblsysbrands tblsysbrands, String locationname, String storecode, String storename, String addressline1, String addressline2, String city, String postalcode, String countrycode, String mainphone, String homepage, Double latitude, Double longitude, Integer locationmaxradius, Boolean approved, Set<Tblbannerlogs> tblbannerlogses, Set<Tblbannerlocations> tblbannerlocationses) {
       this.locationid = locationid;
       this.tblsysbrands = tblsysbrands;
       this.locationname = locationname;
       this.storecode = storecode;
       this.storename = storename;
       this.addressline1 = addressline1;
       this.addressline2 = addressline2;
       this.city = city;
       this.postalcode = postalcode;
       this.countrycode = countrycode;
       this.mainphone = mainphone;
       this.homepage = homepage;
       this.latitude = latitude;
       this.longitude = longitude;
       this.locationmaxradius = locationmaxradius;
       this.approved = approved;
       this.tblbannerlogses = tblbannerlogses;
       this.tblbannerlocationses = tblbannerlocationses;
    }
   
     @Id 
    
     @Column(name="locationid", unique=true, nullable=false,columnDefinition="varchar(36)")
    public String getLocationid() {
        return this.locationid.toString();
    }
    
    public void setLocationid(String locationid) {
        this.locationid = UUID.fromString(locationid);
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brandid", nullable=false)
    public Tblsysbrands getTblsysbrands() {
        return this.tblsysbrands;
    }
    
    public void setTblsysbrands(Tblsysbrands tblsysbrands) {
        this.tblsysbrands = tblsysbrands;
    }
    
    @Column(name="locationname", nullable=false, length=100)
    public String getLocationname() {
        return this.locationname;
    }
    
    public void setLocationname(String locationname) {
        this.locationname = locationname;
    }
    
    @Column(name="storecode", nullable=false, length=30)
    public String getStorecode() {
        return this.storecode;
    }
    
    public void setStorecode(String storecode) {
        this.storecode = storecode;
    }
    
    @Column(name="storename", length=100)
    public String getStorename() {
        return this.storename;
    }
    
    public void setStorename(String storename) {
        this.storename = storename;
    }
    
    @Column(name="addressline1", length=100)
    public String getAddressline1() {
        return this.addressline1;
    }
    
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }
    
    @Column(name="addressline2", length=100)
    public String getAddressline2() {
        return this.addressline2;
    }
    
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }
    
    @Column(name="city", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="postalcode", length=15)
    public String getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }
    
    @Column(name="countrycode", length=3)
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }
    
    @Column(name="mainphone", length=30)
    public String getMainphone() {
        return this.mainphone;
    }
    
    public void setMainphone(String mainphone) {
        this.mainphone = mainphone;
    }
    
    @Column(name="homepage")
    public String getHomepage() {
        return this.homepage;
    }
    
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }
    
    @Column(name="latitude", precision=17, scale=17)
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    
    @Column(name="longitude", precision=17, scale=17)
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    
    @Column(name="locationmaxradius")
    public Integer getLocationmaxradius() {
        return this.locationmaxradius;
    }
    
    public void setLocationmaxradius(Integer locationmaxradius) {
        this.locationmaxradius = locationmaxradius;
    }
    
    @Column(name="approved")
    public Boolean getApproved() {
        return this.approved;
    }
    
    public void setApproved(Boolean approved) {
        this.approved = approved;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbllocations")
    public Set<Tblbannerlogs> getTblbannerlogses() {
        return this.tblbannerlogses;
    }
    
    public void setTblbannerlogses(Set<Tblbannerlogs> tblbannerlogses) {
        this.tblbannerlogses = tblbannerlogses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbllocations")
    public Set<Tblbannerlocations> getTblbannerlocationses() {
        return this.tblbannerlocationses;
    }
    
    public void setTblbannerlocationses(Set<Tblbannerlocations> tblbannerlocationses) {
        this.tblbannerlocationses = tblbannerlocationses;
    }




}


