package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblsysusercompanies generated by hbm2java
 */
@Entity
@Table(name="tblsysusercompanies"
    ,schema="public"
)
public class Tblsysusercompanies  implements Serializable {


     private String userlinkid;
     private Tblsyscompanies tblsyscompanies;
     private AspnetUsers aspnetUsers;

    public Tblsysusercompanies() {
    }

	
    public Tblsysusercompanies(String userlinkid) {
        this.userlinkid = userlinkid;
    }
    public Tblsysusercompanies(String userlinkid, Tblsyscompanies tblsyscompanies, AspnetUsers aspnetUsers) {
       this.userlinkid = userlinkid;
       this.tblsyscompanies = tblsyscompanies;
       this.aspnetUsers = aspnetUsers;
    }
   
     @Id 
    
    @Column(name="userlinkid", unique=true, nullable=false)
    public String getUserlinkid() {
        return this.userlinkid;
    }
    
    public void setUserlinkid(String userlinkid) {
        this.userlinkid = userlinkid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="companyid")
    public Tblsyscompanies getTblsyscompanies() {
        return this.tblsyscompanies;
    }
    
    public void setTblsyscompanies(Tblsyscompanies tblsyscompanies) {
        this.tblsyscompanies = tblsyscompanies;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid")
    public AspnetUsers getAspnetUsers() {
        return this.aspnetUsers;
    }
    
    public void setAspnetUsers(AspnetUsers aspnetUsers) {
        this.aspnetUsers = aspnetUsers;
    }




}


