package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblsyscategories generated by hbm2java
 */
@Entity
@Table(name="tblsyscategories"
    ,schema="public"
)
public class Tblsyscategories  implements java.io.Serializable {


     private int categoryid;
     private String categoryname;
     private Set<Tblsyssubcategories> tblsyssubcategorieses = new HashSet<Tblsyssubcategories>(0);
     private Set<Tblbanners> tblbannerses = new HashSet<Tblbanners>(0);

    public Tblsyscategories() {
    }

	
    public Tblsyscategories(int categoryid) {
        this.categoryid = categoryid;
    }
    public Tblsyscategories(int categoryid, String categoryname, Set<Tblsyssubcategories> tblsyssubcategorieses, Set<Tblbanners> tblbannerses) {
       this.categoryid = categoryid;
       this.categoryname = categoryname;
       this.tblsyssubcategorieses = tblsyssubcategorieses;
       this.tblbannerses = tblbannerses;
    }
   
     @Id 
    
    @Column(name="categoryid", unique=true, nullable=false)
    public int getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(int categoryid) {
        this.categoryid = categoryid;
    }
    
    @Column(name="categoryname", length=50)
    public String getCategoryname() {
        return this.categoryname;
    }
    
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsyscategories")
    public Set<Tblsyssubcategories> getTblsyssubcategorieses() {
        return this.tblsyssubcategorieses;
    }
    
    public void setTblsyssubcategorieses(Set<Tblsyssubcategories> tblsyssubcategorieses) {
        this.tblsyssubcategorieses = tblsyssubcategorieses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsyscategories")
    public Set<Tblbanners> getTblbannerses() {
        return this.tblbannerses;
    }
    
    public void setTblbannerses(Set<Tblbanners> tblbannerses) {
        this.tblbannerses = tblbannerses;
    }




}


