package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblsyssubcategories generated by hbm2java
 */
@Entity
@Table(name="tblsyssubcategories"
    ,schema="public"
)
public class Tblsyssubcategories  implements java.io.Serializable {


     private int subcategoryid;
     private Tblsyscategories tblsyscategories;
     private String subcategoryname;
     private Set<Tblbannersubcateories> tblbannersubcateorieses = new HashSet<Tblbannersubcateories>(0);

    public Tblsyssubcategories() {
    }

	
    public Tblsyssubcategories(int subcategoryid, Tblsyscategories tblsyscategories) {
        this.subcategoryid = subcategoryid;
        this.tblsyscategories = tblsyscategories;
    }
    public Tblsyssubcategories(int subcategoryid, Tblsyscategories tblsyscategories, String subcategoryname, Set<Tblbannersubcateories> tblbannersubcateorieses) {
       this.subcategoryid = subcategoryid;
       this.tblsyscategories = tblsyscategories;
       this.subcategoryname = subcategoryname;
       this.tblbannersubcateorieses = tblbannersubcateorieses;
    }
   
     @Id 
    
    @Column(name="subcategoryid", unique=true, nullable=false)
    public int getSubcategoryid() {
        return this.subcategoryid;
    }
    
    public void setSubcategoryid(int subcategoryid) {
        this.subcategoryid = subcategoryid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoryid", nullable=false)
    public Tblsyscategories getTblsyscategories() {
        return this.tblsyscategories;
    }
    
    public void setTblsyscategories(Tblsyscategories tblsyscategories) {
        this.tblsyscategories = tblsyscategories;
    }
    
    @Column(name="subcategoryname", length=50)
    public String getSubcategoryname() {
        return this.subcategoryname;
    }
    
    public void setSubcategoryname(String subcategoryname) {
        this.subcategoryname = subcategoryname;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsyssubcategories")
    public Set<Tblbannersubcateories> getTblbannersubcateorieses() {
        return this.tblbannersubcateorieses;
    }
    
    public void setTblbannersubcateorieses(Set<Tblbannersubcateories> tblbannersubcateorieses) {
        this.tblbannersubcateorieses = tblbannersubcateorieses;
    }




}


