package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblsysbrands generated by hbm2java
 */
@Entity
@Table(name="tblsysbrands"
    ,schema="public"
)
public class Tblsysbrands  implements java.io.Serializable {


     private int brandid;
     private Tblsyscompanies tblsyscompanies;
     private String brandname;
     private String billingname;
     private String billingemail;
     private String billingtel;
     private String reportingname;
     private String reportingemail;
     private String reportingtel;
     private String creativename;
     private String creativeemail;
     private String creativetel;
     private Set<Tblbanners> tblbannerses = new HashSet<Tblbanners>(0);
     private Set<Tbllocations> tbllocationses = new HashSet<Tbllocations>(0);

    public Tblsysbrands() {
    }

	
    public Tblsysbrands(int brandid, Tblsyscompanies tblsyscompanies) {
        this.brandid = brandid;
        this.tblsyscompanies = tblsyscompanies;
    }
    public Tblsysbrands(int brandid, Tblsyscompanies tblsyscompanies, String brandname, String billingname, String billingemail, String billingtel, String reportingname, String reportingemail, String reportingtel, String creativename, String creativeemail, String creativetel, Set<Tblbanners> tblbannerses, Set<Tbllocations> tbllocationses) {
       this.brandid = brandid;
       this.tblsyscompanies = tblsyscompanies;
       this.brandname = brandname;
       this.billingname = billingname;
       this.billingemail = billingemail;
       this.billingtel = billingtel;
       this.reportingname = reportingname;
       this.reportingemail = reportingemail;
       this.reportingtel = reportingtel;
       this.creativename = creativename;
       this.creativeemail = creativeemail;
       this.creativetel = creativetel;
       this.tblbannerses = tblbannerses;
       this.tbllocationses = tbllocationses;
    }
   
     @Id 
    
    @Column(name="brandid", unique=true, nullable=false)
    public int getBrandid() {
        return this.brandid;
    }
    
    public void setBrandid(int brandid) {
        this.brandid = brandid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="companyid", nullable=false)
    public Tblsyscompanies getTblsyscompanies() {
        return this.tblsyscompanies;
    }
    
    public void setTblsyscompanies(Tblsyscompanies tblsyscompanies) {
        this.tblsyscompanies = tblsyscompanies;
    }
    
    @Column(name="brandname", length=50)
    public String getBrandname() {
        return this.brandname;
    }
    
    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }
    
    @Column(name="billingname", length=50)
    public String getBillingname() {
        return this.billingname;
    }
    
    public void setBillingname(String billingname) {
        this.billingname = billingname;
    }
    
    @Column(name="billingemail", length=50)
    public String getBillingemail() {
        return this.billingemail;
    }
    
    public void setBillingemail(String billingemail) {
        this.billingemail = billingemail;
    }
    
    @Column(name="billingtel", length=20)
    public String getBillingtel() {
        return this.billingtel;
    }
    
    public void setBillingtel(String billingtel) {
        this.billingtel = billingtel;
    }
    
    @Column(name="reportingname", length=50)
    public String getReportingname() {
        return this.reportingname;
    }
    
    public void setReportingname(String reportingname) {
        this.reportingname = reportingname;
    }
    
    @Column(name="reportingemail", length=50)
    public String getReportingemail() {
        return this.reportingemail;
    }
    
    public void setReportingemail(String reportingemail) {
        this.reportingemail = reportingemail;
    }
    
    @Column(name="reportingtel", length=20)
    public String getReportingtel() {
        return this.reportingtel;
    }
    
    public void setReportingtel(String reportingtel) {
        this.reportingtel = reportingtel;
    }
    
    @Column(name="creativename", length=50)
    public String getCreativename() {
        return this.creativename;
    }
    
    public void setCreativename(String creativename) {
        this.creativename = creativename;
    }
    
    @Column(name="creativeemail", length=50)
    public String getCreativeemail() {
        return this.creativeemail;
    }
    
    public void setCreativeemail(String creativeemail) {
        this.creativeemail = creativeemail;
    }
    
    @Column(name="creativetel", length=20)
    public String getCreativetel() {
        return this.creativetel;
    }
    
    public void setCreativetel(String creativetel) {
        this.creativetel = creativetel;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsysbrands")
    public Set<Tblbanners> getTblbannerses() {
        return this.tblbannerses;
    }
    
    public void setTblbannerses(Set<Tblbanners> tblbannerses) {
        this.tblbannerses = tblbannerses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsysbrands")
    public Set<Tbllocations> getTbllocationses() {
        return this.tbllocationses;
    }
    
    public void setTbllocationses(Set<Tbllocations> tbllocationses) {
        this.tbllocationses = tbllocationses;
    }




}


