package com.sdk.service;
// Generated Aug 1, 2014 11:59:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblsyscompanies generated by hbm2java
 */
@Entity
@Table(name="tblsyscompanies"
    ,schema="public"
)
public class Tblsyscompanies  implements java.io.Serializable {


     private int companyid;
     private String companyname;
     private String contactperson;
     private String contactphone;
     private String contactemail;
     private String accountperson;
     private String accountphone;
     private String accountemail;
     private String currency;
     private String address1;
     private String address2;
     private String postcode;
     private String city;
     private String province;
     private String country;
     private String clienttype;
     private Set<Tblsysusercompanies> tblsysusercompanieses = new HashSet<Tblsysusercompanies>(0);
     private Set<Tblsysbrands> tblsysbrandses = new HashSet<Tblsysbrands>(0);

    public Tblsyscompanies() {
    }

	
    public Tblsyscompanies(int companyid) {
        this.companyid = companyid;
    }
    public Tblsyscompanies(int companyid, String companyname, String contactperson, String contactphone, String contactemail, String accountperson, String accountphone, String accountemail, String currency, String address1, String address2, String postcode, String city, String province, String country, String clienttype, Set<Tblsysusercompanies> tblsysusercompanieses, Set<Tblsysbrands> tblsysbrandses) {
       this.companyid = companyid;
       this.companyname = companyname;
       this.contactperson = contactperson;
       this.contactphone = contactphone;
       this.contactemail = contactemail;
       this.accountperson = accountperson;
       this.accountphone = accountphone;
       this.accountemail = accountemail;
       this.currency = currency;
       this.address1 = address1;
       this.address2 = address2;
       this.postcode = postcode;
       this.city = city;
       this.province = province;
       this.country = country;
       this.clienttype = clienttype;
       this.tblsysusercompanieses = tblsysusercompanieses;
       this.tblsysbrandses = tblsysbrandses;
    }
   
     @Id 
    
    @Column(name="companyid", unique=true, nullable=false)
    public int getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(int companyid) {
        this.companyid = companyid;
    }
    
    @Column(name="companyname", length=50)
    public String getCompanyname() {
        return this.companyname;
    }
    
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
    
    @Column(name="contactperson", length=50)
    public String getContactperson() {
        return this.contactperson;
    }
    
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson;
    }
    
    @Column(name="contactphone", length=20)
    public String getContactphone() {
        return this.contactphone;
    }
    
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone;
    }
    
    @Column(name="contactemail", length=50)
    public String getContactemail() {
        return this.contactemail;
    }
    
    public void setContactemail(String contactemail) {
        this.contactemail = contactemail;
    }
    
    @Column(name="accountperson", length=50)
    public String getAccountperson() {
        return this.accountperson;
    }
    
    public void setAccountperson(String accountperson) {
        this.accountperson = accountperson;
    }
    
    @Column(name="accountphone", length=20)
    public String getAccountphone() {
        return this.accountphone;
    }
    
    public void setAccountphone(String accountphone) {
        this.accountphone = accountphone;
    }
    
    @Column(name="accountemail", length=50)
    public String getAccountemail() {
        return this.accountemail;
    }
    
    public void setAccountemail(String accountemail) {
        this.accountemail = accountemail;
    }
    
    @Column(name="currency", length=3)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    
    @Column(name="address1", length=100)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    
    @Column(name="address2", length=100)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    
    @Column(name="postcode", length=10)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    
    @Column(name="city", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="province", length=50)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    
    @Column(name="country", length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="clienttype", length=50)
    public String getClienttype() {
        return this.clienttype;
    }
    
    public void setClienttype(String clienttype) {
        this.clienttype = clienttype;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsyscompanies")
    public Set<Tblsysusercompanies> getTblsysusercompanieses() {
        return this.tblsysusercompanieses;
    }
    
    public void setTblsysusercompanieses(Set<Tblsysusercompanies> tblsysusercompanieses) {
        this.tblsysusercompanieses = tblsysusercompanieses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsyscompanies")
    public Set<Tblsysbrands> getTblsysbrandses() {
        return this.tblsysbrandses;
    }
    
    public void setTblsysbrandses(Set<Tblsysbrands> tblsysbrandses) {
        this.tblsysbrandses = tblsysbrandses;
    }




}


